package presentation;


import business.Logic;
import business.ConnectionDB;
import domain.Cuenta;
import domain.Planes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fava_
 */
public class EditGUI extends javax.swing.JFrame {
    Cuenta c;
    /**
     * Creates new form AccountGUI
     */
    public EditGUI() {
       
        initComponents();
        
        
        
        ArrayList<Planes> plan = Logic.getPlan();
        for(int i = 0; i<plan.size(); i++){
        cbPlan.addItem(String.valueOf(plan.get(i).getTypePlan()));
        }
        
        ArrayList<Cuenta> cuentas = Logic.searchCuenta(Integer.valueOf(PrincipalGUI.tfCode.getText()));
        
        tfName.setText(cuentas.get(0).getName());
        tfLastName.setText(cuentas.get(0).getLastName());
        tfEmail.setText(cuentas.get(0).getEmail());
        
        cbPlan.setSelectedIndex(cuentas.get(0).getPlanCode()-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbPlan = new javax.swing.JComboBox<>();
        bUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 69, -1));

        tfName.setBackground(new java.awt.Color(51, 51, 51));
        tfName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setBorder(null);
        tfName.setEnabled(false);
        jPanel1.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 377, 46));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LastName:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 98, -1));

        tfLastName.setBackground(new java.awt.Color(51, 51, 51));
        tfLastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfLastName.setForeground(new java.awt.Color(255, 255, 255));
        tfLastName.setBorder(null);
        tfLastName.setEnabled(false);
        jPanel1.add(tfLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 377, 49));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 63, -1));

        tfEmail.setBackground(new java.awt.Color(51, 51, 51));
        tfEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfEmail.setBorder(null);
        tfEmail.setEnabled(false);
        tfEmail.setMaximumSize(new java.awt.Dimension(32767, 32767));
        tfEmail.setMinimumSize(new java.awt.Dimension(72, 22));
        tfEmail.setPreferredSize(new java.awt.Dimension(72, 22));
        jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 377, 54));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Plan:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 53, -1));

        cbPlan.setBackground(new java.awt.Color(255, 51, 51));
        cbPlan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbPlan.setForeground(new java.awt.Color(255, 255, 255));
        cbPlan.setBorder(null);
        cbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanActionPerformed(evt);
            }
        });
        jPanel1.add(cbPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 377, 43));

        bUpdate.setBackground(new java.awt.Color(255, 0, 0));
        bUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bUpdate.setForeground(new java.awt.Color(255, 255, 255));
        bUpdate.setText("Actualizar");
        bUpdate.setToolTipText("");
        bUpdate.setBorder(null);
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(bUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 377, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 620, 710));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/log.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, 170, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/netflixback.jpg"))); // NOI18N
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        // TODO add your handling code here:
        int code = 0;
        Statement stmt;
        try {
            stmt = ConnectionDB.getInstance().getConnection().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM planes p where p.nombre = '"+cbPlan.getSelectedItem().toString()+"'");
            while(rs.next()){
            code = rs.getInt("codigo");
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
               
        c = new Cuenta(Integer.valueOf(PrincipalGUI.tfCode.getText()),code,tfName.getText(),tfLastName.getText(),tfEmail.getText());
        
        Logic.UpdateCuenta(c);
       
        this.dispose();
    }//GEN-LAST:event_bUpdateActionPerformed

    private void cbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox<String> cbPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
