package presentation;


import business.ConnectionDB;
import business.Logic;
import domain.Cuenta;
import domain.Planes;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fava_
 */
public class PrincipalGUI extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
        initTable("all");
    }
    
    public void initTable(String type){
    
        dtm = new DefaultTableModel();
        String title[]={"CodeC","Plan","Nombre","Apellido","Correo"};
        dtm.setColumnIdentifiers(title);
        Statement stmt = null;
        try {
            stmt = ConnectionDB.getInstance().getConnection().createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        switch(type){
            case "all":
            try {
   
                 ResultSet rs = stmt.executeQuery("SELECT c.codigoCuenta, p.nombre as nombrePlan,c.nombre,c.apellido,c.correo from cuenta c inner join planes p on c.codigoPlan = p.codigo");
                   while(rs.next()){
                    Object[] data = {rs.getString("codigoCuenta"),rs.getString("nombrePlan"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("correo")};
                    dtm.addRow(data);
               
            }
            } catch (SQLException ex) {
                Logger.getLogger(PrincipalGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           /* 
        for (Cuenta object : Logic.getCuenta()) {
            Object[] data = {object.getCode(),object.getPlanCode(),object.getName(),object.getLastName(),object.getEmail()};
            dtm.addRow(data);
        }
        */
             break;
        
            case "search":
                
            try {
                 ResultSet rs = stmt.executeQuery("SELECT c.codigoCuenta, p.nombre as nombrePlan,c.nombre,c.apellido,c.correo from cuenta c inner join planes p on c.codigoPlan = p.codigo where c.codigoCuenta = "+tfCode.getText());
                   while(rs.next()){
                    Object[] data = {rs.getString("codigoCuenta"),rs.getString("nombrePlan"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("correo")};
                    dtm.addRow(data);
               
            }
            } catch (SQLException ex) {
                Logger.getLogger(PrincipalGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                
       
            
            break;
}
        tCounts.setModel(dtm);
        tCounts.getTableHeader().setReorderingAllowed(false);
        tCounts.getTableHeader().setBackground(Color.black);
        tCounts.getTableHeader().setForeground(Color.white);
        tCounts.setOpaque(false);
        ((DefaultTableCellRenderer)tCounts.getDefaultRenderer(Object.class)).setOpaque(false);
        sptCounts.setOpaque(false);
        sptCounts.getViewport().setOpaque(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sptCounts = new javax.swing.JScrollPane();
        tCounts = new javax.swing.JTable();
        bRegister = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        tfCode = new javax.swing.JTextField();
        bSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sptCounts.setBorder(null);

        tCounts.setBackground(new java.awt.Color(0, 0, 0));
        tCounts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tCounts.setForeground(new java.awt.Color(255, 255, 255));
        tCounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sptCounts.setViewportView(tCounts);

        jPanel1.add(sptCounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 610, -1));

        bRegister.setBackground(new java.awt.Color(255, 51, 51));
        bRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bRegister.setForeground(new java.awt.Color(255, 255, 255));
        bRegister.setText("Sign in");
        bRegister.setBorder(null);
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(bRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 100, 30));

        bRefresh.setBackground(new java.awt.Color(0, 0, 0));
        bRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bRefresh.setForeground(new java.awt.Color(255, 255, 255));
        bRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/refresh.png"))); // NOI18N
        bRefresh.setBorder(null);
        bRefresh.setBorderPainted(false);
        bRefresh.setFocusPainted(false);
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(bRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 60, 40));

        bDelete.setBackground(new java.awt.Color(0, 0, 0));
        bDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDelete.setForeground(new java.awt.Color(255, 255, 255));
        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        bDelete.setBorder(null);
        bDelete.setBorderPainted(false);
        bDelete.setFocusPainted(false);
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 50, 40));

        tfCode.setBackground(new java.awt.Color(51, 51, 51));
        tfCode.setForeground(new java.awt.Color(255, 255, 255));
        tfCode.setBorder(null);
        jPanel1.add(tfCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 30));

        bSearch.setBackground(new java.awt.Color(0, 0, 0));
        bSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSearch.setForeground(new java.awt.Color(255, 255, 255));
        bSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        bSearch.setBorder(null);
        bSearch.setBorderPainted(false);
        bSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bSearch.setFocusPainted(false);
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });
        jPanel1.add(bSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 60, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestor de Datos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bitmap.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bLogin.setBackground(new java.awt.Color(255, 51, 51));
        bLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setText("Login");
        bLogin.setBorder(null);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        jPanel1.add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 100, 30));

        bUpdate.setBackground(new java.awt.Color(0, 0, 0));
        bUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        bUpdate.setBorder(null);
        bUpdate.setBorderPainted(false);
        bUpdate.setFocusPainted(false);
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(bUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 690, 670));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/netflixback.jpg"))); // NOI18N
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
      AccountGUI gui = new AccountGUI();
      gui.setVisible(true);
    }//GEN-LAST:event_bRegisterActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        initTable("all");
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        // TODO add your handling code here:
        initTable("search");
    }//GEN-LAST:event_bSearchActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        Logic.deleteCuenta(Integer.valueOf(tfCode.getText()));
        initTable("all");
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        // TODO add your handling code here:
        EditGUI eGUI = new EditGUI();
        eGUI.setVisible(true);
    }//GEN-LAST:event_bUpdateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bRegister;
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane sptCounts;
    private javax.swing.JTable tCounts;
    public static javax.swing.JTextField tfCode;
    // End of variables declaration//GEN-END:variables
}
